apiVersion: v1
kind: Service

metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
